version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql:5.7.5
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - mysql_data:/var/lib/mysql_data/data/
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=hello_django
      - MYSQL_PASSWORD=hello_django
      - MYSQL_DATABASE=hello_django_dev

volumes:
  mysql_data:
