version: '3.7'

services:

  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - tf
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=lepi_pass
      - POSTGRES_DB=biodex_dev
  tf:
    image: biodex/prediction_model:latest
    ports:
      - 8501:8501

volumes:
  postgres_data:
